[package]
name = "log_cs2"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.3"
notify = "6.1.1"
notify-debouncer-full = "0.3.1"
ratatui = "0.27.0"
regex = "1.10.5"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.122"
strip-ansi-escapes = "0.2.0"
